# Site settings
name: C S Q
email: 1290411089@qq.com
author: Freud Chen
url: http://www.csqiang.top
resume_site: https://csqiang123.github.io/csiqang.github.io/
github: https://github.com/csqiang123/
baseurl: "/csiqang.github.io"
description: Actually, less is more!
meta_description: Csqiang;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: csqiang123

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

